### ISSUE TITLE
Translation file format

### ISSUE THREAD

**Issue by equaa** [le-doux/bitsy#134]
I'd like to contribute a translation of Bitsy for a project some time in the future, and the .tsv file format is getting pretty unwieldy to navigate. I can see its benefits (having all of the translations side-by-side so that unfinished translations are clearly marked?) but it's pretty hard to edit without specialized tools (a spreadsheet vs. like, a text editor), and it doesn't play with git too well either: since every language's translation is in the same line, there's a lot of irrelevant stuff filling the git diffs, merge conflicts are far more likely, etc. Is there some workflow reason that you want to keep it as one large tsv? Would you accept a patch changing it to something else, and if so, what would the requirements be for that?

**Comment by le-doux** [comment]
hi @equaa this is a good question! :)

the reason for the TSV was because the original work to translate bitsy was done in a google spreadsheet, which was convenient since collaboration was easy and not everyone involved was necessarily a github user

however, that google spreadsheet hasn't been used actively for a while and as you note the TSV has gotten quite large, so I'm definitely open to the idea of switching to a different format / workflow for localization

I think the main requirement I can think of off the top of my head is we'd need a user friendly way to contribute localizations

I'm not sure what this would look like but I'm open to suggestions if you want to discuss! :)
