### ISSUE TITLE
Loading project problems in version 7.11

### ISSUE THREAD

**Issue by AndreaTupacMollica** [le-doux/bitsy#142]
Hi Adam!
In version 7.11, when I load a game downloaded as .html, I just see the default new game room, so the loading seems to have failed.

The same happens if I start a project anew, develop it a bit, save it and then try to load it again.

I'm a Mac user (Monterey) and I'v seen this issue both with the Safari and the Chrome Browser!

Thanks for the help!

**Comment by equaa** [comment]
proposed fix in #143

**Comment by equaa** [comment]
hello @AndreaTupacMollica! i can explain more about how the fix works, but if you just want to use it, i put it up to use here until it's fixed in the main bitsy: https://equa.space/bitsy-save-fix/ it's the same as bitsy 7.11 otherwise, just with the fix. even your old broken save files should load fine in the patched version :)

---

if you have git installed on your computer (i'm not sure how to install it on a Mac though), you could also download it from the Github by running these commands:
```
git clone https://github.com/equaa/bitsy/ # this clones all of the code
cd bitsy # and enters it
git checkout fix-save # this enters the "branch" where i fix the save code
```
after that you could just open the `editor/index.html` file on your web browser

---

as for how the fix actually works? it's a little bit complicated, but i can try to explain it in more depth. hopefully it's interesting!

so, when viewing text files, computers have two different main ways of representing when one line of text ends, and another begins. on almost all Unix systems (including, say, Mac and Linux systems), a single `0A` byte in a file says that the line has ended, and to start on a new one. but on Windows systems, this needs two bytes: `0D 0A`. this simple difference can lead to a lot of problems: if I make a text file on my Linux computer and then hand it to my Windows-using friend, the newlines in *my* system will all just display as a single line on hers.

to prevent this problem, Git has a little clever trick: when passing files back and forth, it automatically converts the newlines to the one that's right to your system. if I make a file with `0A` newlines, push it to Git, and then send it to my friend, they'll see a `0D 0A`.

this is great! most of our problems are solved cleanly. but one of the processes that makes Bitsy work doesn't handle it as well--it just places a bunch of files in a big database for the editor to read. so when you run the database maker on Linux or a Mac, you'll get a database full of `0A` newlines, and when you run it on Windows, you'll get one full of `0D 0A`. one of the files in this database is the *template* for saving your game. the editor takes that template, patches in the game data, and then gives you that file.

so in old versions of Bitsy, the database had newlines using `0A`, so your exported file might look like this.
```
<script type="text/bitsyGameData" id="exportedGameData">[0A]
my game[0A]
[0A]
# BITSY VERSION 7.11[0A]
etc.
```

but in new versions, you get something like this:

```
<script type="text/bitsyGameData" id="exportedGameData">[0D 0A]
my game[0D 0A]
[0D 0A]
# BITSY VERSION 7.11[0D 0A]
etc.
```

this file *looks* similar, and a web browser like Firefox or Safari is used to these differences, so when you *play* the game, it works fine. but when you *import* the game to work on it, Bitsy tries to look for a specific string to figure out where the game's data is. it looks for this: `<script type="text/bitsyGameData" id="exportedGameData">[0A]`

now the problem should be pretty clear: our new exported files end in `0D 0A`, so Bitsy can't find the game data!

the fix is pretty simple. all I did was make the import script recognize those special newlines. i also made it so that the database-maker doesn't output them anymore--this way it works *exactly* the same, regardless of whether the person making the software is on Windows or not.

---

oops, this explanation got a little long-winded. i hope this was helpful for you!

**Comment by allthegoodonesaretaken** [comment]
> 

Literally made an account just to say thank you so so much. I'm doing an assignment using Bitsy and you actually just saved my ass with this, I'm not kidding when I say I would have lost days of (fun) work. Thank you so much love u

**Comment by AndreaTupacMollica** [comment]
Thank you @equaa! I'll try your fix at once. Thanks again!

**Comment by le-doux** [comment]
this was fixed by @equaa a while ago but I forgot to close it - closing now :)

(fix: https://github.com/le-doux/bitsy/pull/143)
