### ISSUE TITLE
Clicking on "Exits and endings" in room module stops placement of tiles etc

### ISSUE THREAD

**Issue by GaryGr** [le-doux/bitsy#181]
When I click on/activate the "Exits and endings" button in the room module, I can then no longer place titles, items or sprites, and have to refresh the web page to get it to work properly again.

**Comment by le-doux** [comment]
hiya - thanks for the write-up! :)

I _think_ what you're describing is actually an intentional change. starting in v8.0, the "exits and endings" mode in the room tool now disables painting - this is intended to make it harder to accidentally paint tiles when you're trying to click & drag exit positions.

to turn back on the tile painting mode, switch back to the "paint" mode and it should work as normal. you shouldn't have to refresh the page (if you do that's definitely a bug!)

this is a change from how things used to work, so if you have any suggestions on how to make it clearer what's happening, I'm interested to hear them! :D

**Comment by GaryGr** [comment]
Thanks for clarifying that, Adam. :) I hadn't realised that's how it worked now. I'm not sure it needs to be made more obvious - as long as it's in the documentation that's probably fine.

**Comment by le-doux** [comment]
sounds good! I'm going to close this for now then - feel free to open another issue later if you have usability suggestions related to this though :)
