### ISSUE TITLE
Special parsing for tile id `0`

### ISSUE THREAD

**Issue by ace-dent** [le-doux/bitsy#188]
Feature / enhancement request:
It is desirable to copy & paste tile data from external sources, into the `Game Data` of the main Bitsy editor. 
This may be from other graphic libraries, converter programs, etc.
However, it is unknown to an external source how to number the base36 id, to avoid colliding with existing id's in the Bitsy editor.

Currently tile id zero (`TIL 0`) is reserved, and treated as blank in the game map data.  It should not exist in the tile set.

Proposal:
On parsing updated (copy&pasted) tile data, any tiles assigned an id of `0`, should be assigned new id's, based on current automatic generation.

e.g.
```text
TIL 0
00000000
00001010
00000100
00000000
00000000
10100000
01000000
00000000
NAME grass

TIL 0
00000000
00000000
00000000
00000000
00000100
01001000
00101000
00000000
NAME tuffet
```

– Might be assigned `TIL b` and `TIL c`.

I'm not sure whether this requirement exists for other object types...

**Comment by ace-dent** [comment]
An alternative scheme, which allows the export to show preferred order, is to prefix with a special character like `$` or `#` ( or `€` for exported?) followed by the normal base36 number. Any special character handling may affect bug #187.   

e.g.

```
TIL $1
00000000
00001010
00000100
00000000
00000000
10100000
01000000
00000000
NAME grass

TIL $2
00000000
00000000
00000000
00000000
00000100
01001000
00101000
00000000
NAME tuffet
```

On detecting the `$`, the objects will be assigned the next free ids, in sequence.

**Comment by le-doux** [comment]
thanks for the proposals!

your goal makes sense, but I don't currently want to add any more workflows that require manually editing the game data, since many people use the GUI only. also those features tend to break, since it's easy for me to forget them when testing.

a built-in GUI for importing individual tiles or other types of game data is another option, but it is a significant amount of work. in addition, since there are externals tools such as bitsy merge tool (https://seansleblanc.itch.io/bitsy-merge) and mixsy (https://ruin.itch.io/mixsy) that address this need, this is not a high priority for me currently.

given all that, I don't see myself taking this issue on near term, so I'm closing it for now

thanks again for the suggestion and the detailed write-up - I really do appreciate it!
