### ISSUE TITLE
Using "Unicode Asian" font, multiline text does not  be drawn correctly.

### ISSUE THREAD

**Issue by masushin** [le-doux/bitsy#194]
Using "Unicode Asian" font, multiline text can’t be drawn correctly.

1. Specifies “Unicode Asian” font on settings window, 

2. Puts multiline text to the dialog includes Asian characters.
( ex. "あいうえおあいうえおあいうえおあいうえお" ).

3. Text does not be drawn correctly. It seems that break line can’t work correctly.

https://user-images.githubusercontent.com/18723885/200115606-c9ac3689-c442-41ee-a084-71b7be217282.mp4

**Comment by le-doux** [comment]
thanks for the bug report!

I think that what you're seeing happens because line breaks only happen if you insert a space

is that a reasonable workaround? or do you think the line wrap logic should be different for "unicode asian"?

this isn't a subject I have expertise in, so any feedback you have would be appreciated :)

**Comment by masushin** [comment]
I see. word wrap.

I confirmed that the same phenomenon occurs when I display a long non-Japanese text without spaces, such as "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" in AsciiFont.

Japanese text usually does not use spaces to separate words. So this specification for text drawing cannot  display the Japanese correctly.

I hope it will be fix ..

**Comment by le-doux** [comment]
thanks for the testing and explanation @masushin - this is super helpful for me!

I'd definitely like to fix this in a future update, so that Japanese can display correctly. here's my idea of how I could handle it: I can add an additional text rendering option in the settings menu that always forces text to wrap when it exceeds the maximum line length, instead of only wrapping on words. then for languages such as Japanese where it's known that this is needed, Bitsy will turn that setting on by default. do you think that would be a good solution? let me know if you have any suggestions!

**Comment by masushin** [comment]
thank you for your considerarion.

I think your idea is enough to display text for japanese and any other language which not use space between words.

**Comment by le-doux** [comment]
thanks for your feedback! :)

**Comment by david-c14** [comment]
In most places you can add an explicit line break using {br}.   That's what I've suggested to people in the past when using written languages with this kind of structure.

It's a more explicit workaround that using a space.

**Comment by le-doux** [comment]
since the fix for this is ambiguous and we have a workaround, I'm closing this for now - can revisit later
