### ISSUE TITLE
when you start a new game, sometimes old dialog sticks around

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#20]

**Comment by Ragzouken** [comment]
Can't seem to replicate this, though I noticed that the "new game" button doesn't stop you being in play mode. Wasn't able to make any funny business happen due to that though.

`resetGameData` does seem to do what you'd expect, so if this bug is still in there somewhere I'd guess it's an input box edit event firing after the reset--but I couldn't get it to happen for me

**Comment by le-doux** [comment]
thanks for trying this @Ragzouken - I'm going to close it as not repro-ing :)
