### ISSUE TITLE
Bitsy documentation is broken 

### ISSUE THREAD

**Issue by ValorZard** [le-doux/bitsy#247]
A lot of the images are missing from some of the pages, and some pages straight up wont load
![image](https://github.com/le-doux/bitsy/assets/7539214/88045f9d-4301-402a-8619-9ab7972f8e63)

**Comment by seleb** [comment]
this might be bc there was a new release about an hour ago? if you were using the make.bitsy.org site instead of itch and had the tab open when the release happened, it's possible you're trying to access files from the old version (8.7) that no longer exist. if you refresh and confirm you're on the latest version (8.8), do you still see the issue?

**Comment by ValorZard** [comment]
Okay it seems fine now. Must have been it!
