### ISSUE TITLE
Editor changing tile ids when exporting game or copy/pasting game data

### ISSUE THREAD

**Issue by thatguynm** [le-doux/bitsy#50]
Sometimes the editor will add an extra letter to a tile within a room (typically a duplicate letter/number). The changed tile is usually one from the right side of the room.

Has happened both when exporting and when pasting game data into an html file. I've only tested it on chrome, so I'm not sure if it's an issue specific to that browser or not.

![bitsy bug](https://user-images.githubusercontent.com/20374428/66598797-73e42080-eb67-11e9-8a2d-0bacef2b26b1.jpg)

**Comment by seleb** [comment]
hey, we chatted about this issue some more on the discord and potentially found the source of the problem: when you drag past the right side of a room, it adds an extra tile that doesn't actually exist in the map

![](https://media.discordapp.net/attachments/379344247125573634/634471088163651595/GIF.gif)

it's not exactly the same as the original bug since it's still adding the correct tile indices, just further than they're supposed to go, but wouldn't be surprised if it's the root cause of the issue
