### ISSUE TITLE
New Exit from Dialog Option - Dialog box apperears in origin and destination

### ISSUE THREAD

**Issue by afternoonyez** [le-doux/bitsy#83]
Hi Adam, 

First of all thank you for your work on Bitsy. I have been using it as an educator and my students have had a blast. 

I love the improvements you have made, but I am having an issue which may be a bug. 

When I use exit from dialog in a branching list after some initial dialog, the dialog box appears both in the room of origin and the destination. In the room of origin the dialog appears at the bottom of the screen. In the destination the same dialog appears at the top of the screen. I tried to take screenshots of dialog box in the room designated as the exit, but I believe that the key press to trigger the screenshot is removing the dialog box from the screenshot. I am attaching I screenshot of the logic in the dialog box and I do 
have screen capture which shows the process, but I can't seem to upload the video.  

<img width="442" alt="exit_logic_bitsy" src="https://user-images.githubusercontent.com/63878889/79611935-49989000-80c1-11ea-8603-34618ec347e5.png">

Best, 

Eric

**Comment by le-doux** [comment]
Hi Eric,

Thanks for the bug report and I'm glad you and your students are enjoying using Bitsy! :D

I see why this behavior would be unexpected, but I don't think it's a bug. That's because the "exit" command runs immediately and moves the player to the new room without waiting for the dialog to complete. If you want that behavior instead, you need to insert a "pagebreak" command before the exit command, then the player will be required to finish the page before they are moved to the next room. I hope that helps!

(All that said, I see how this might not be intuitive... it's something I'm thinking about for usability.)

Adam
