### ISSUE TITLE
bitsy on itch doesn't always work on firefox

### ISSUE THREAD

**Issue by le-doux** [le-doux/bitsy#96]
but does on ledoux.io -- why?

**Comment by synth-ruiner** [comment]
I believe it's because Itch hosts web content on an external CDN and my Firefox settings block cookies from unvisited websites.

```
Request to access cookie or storage on “https://v6p9d9t4.ssl.hwcdn.net/html/2290891/editor/index.html?v=1591301608” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
```

![Screenshot from 2020-06-17 17-37-24](https://user-images.githubusercontent.com/8642013/84925814-66057880-b0c2-11ea-9b2f-ec422a38acb3.png)

out of curiosity I set my cookie preferences back to standard, and Bitsy worked on Itch again.

so I don't think this is a problem with anything you've done- just a conflict between the way Itch does things and a user preference for blocking external cookies. I think as more people get wise (and more browsers increase their default security settings) this problem might start popping up more often.

this is probably the root cause of #94 too...

**Comment by le-doux** [comment]
thanks for looking into this and for the thorough investigation! :) maybe there's a way I can detect when this happens and let people know in the UI so at least it doesn't look so buggy

**Comment by le-doux** [comment]
I think that @seleb fixed this a while back - closing :)
